import type { LucideIcon } from "lucide-react";
import {
  BookOpen,
  Building2,
  CalendarCheck,
  CreditCard,
  FileBarChart,
  GraduationCap,
  LayoutDashboard,
  MessageSquareWarning,
  Megaphone,
  Receipt,
  Settings,
  Users,
} from "lucide-react";

export type NavItem = {
  label: string;
  href: string;
  icon: LucideIcon;
};

export const navByRole: Record<string, NavItem[]> = {
  SUPER_ADMIN: [
    { label: "Dashboard", href: "/super-admin/dashboard", icon: LayoutDashboard },
  ],
  SCHOOL_ADMIN: [
    { label: "Dashboard", href: "/admin/dashboard", icon: LayoutDashboard },
    { label: "Students", href: "/admin/students", icon: Users },
    { label: "Parents", href: "/admin/parents", icon: Users },
    { label: "Teachers", href: "/admin/teachers", icon: GraduationCap },
    { label: "Classes", href: "/admin/classes", icon: Building2 },
    { label: "Subjects", href: "/admin/subjects", icon: BookOpen },
    { label: "Fees", href: "/admin/fees", icon: CreditCard },
    { label: "Invoices", href: "/admin/invoices", icon: Receipt },
    { label: "Payments", href: "/admin/payments", icon: CreditCard },
    { label: "Results", href: "/admin/results", icon: FileBarChart },
    { label: "Report Cards", href: "/admin/results", icon: FileBarChart },
    { label: "Timetable", href: "/admin/classes", icon: CalendarCheck },
    { label: "LMS", href: "/admin/lms", icon: BookOpen },
    { label: "Attendance", href: "/admin/attendance", icon: CalendarCheck },
    { label: "Messages", href: "/admin/announcements", icon: Megaphone },
    { label: "Announcements", href: "/admin/announcements", icon: Megaphone },
    { label: "Settings", href: "/admin/settings", icon: Settings },
    { label: "Academic Calendar", href: "/admin/settings/academic-calendar", icon: CalendarCheck },
    { label: "Branding", href: "/admin/settings/branding", icon: Settings },
  ],
  PRINCIPAL: [
    { label: "Dashboard", href: "/admin/dashboard", icon: LayoutDashboard },
    { label: "Academic Calendar", href: "/admin/settings/academic-calendar", icon: CalendarCheck },
  ],
  ACCOUNTANT: [
    { label: "Dashboard", href: "/accountant/dashboard", icon: LayoutDashboard },
    { label: "Fee Setup", href: "/accountant/fee-setup", icon: CreditCard },
    { label: "Invoices", href: "/accountant/invoices", icon: Receipt },
    { label: "Payments", href: "/accountant/payments", icon: CreditCard },
    { label: "Receipts", href: "/accountant/receipts", icon: Receipt },
    { label: "Debtors", href: "/accountant/debtors", icon: FileBarChart },
    { label: "Discounts", href: "/accountant/discounts", icon: CreditCard },
    { label: "Finance Reports", href: "/accountant/finance-reports", icon: FileBarChart },
  ],
  TEACHER: [
    { label: "Dashboard", href: "/teacher/dashboard", icon: LayoutDashboard },
    { label: "My Classes", href: "/teacher/my-classes", icon: Building2 },
    { label: "My Subjects", href: "/teacher/my-subjects", icon: BookOpen },
    { label: "Attendance", href: "/teacher/attendance", icon: CalendarCheck },
    { label: "Score Entry", href: "/teacher/score-entry", icon: FileBarChart },
    { label: "Assignments", href: "/teacher/assignments", icon: BookOpen },
    { label: "Lesson Notes", href: "/teacher/lesson-notes", icon: BookOpen },
    { label: "Timetable", href: "/teacher/timetable", icon: CalendarCheck },
    { label: "Student Reports", href: "/teacher/student-reports", icon: FileBarChart },
    { label: "LMS", href: "/teacher/lms", icon: BookOpen },
    { label: "Announcements", href: "/teacher/announcements", icon: Megaphone },
  ],
  PARENT: [
    { label: "Dashboard", href: "/parent/dashboard", icon: LayoutDashboard },
    { label: "Profile", href: "/parent/profile", icon: Users },
    { label: "My Children", href: "/parent/children", icon: Users },
    { label: "Fees & Invoices", href: "/parent/fees", icon: CreditCard },
    { label: "Payments", href: "/parent/payments", icon: CreditCard },
    { label: "Attendance", href: "/parent/attendance", icon: CalendarCheck },
    { label: "Results", href: "/parent/results", icon: FileBarChart },
    { label: "Report Cards", href: "/parent/report-cards", icon: FileBarChart },
    { label: "School Calendar", href: "/parent/school-calendar", icon: CalendarCheck },
    { label: "Messages", href: "/parent/messages", icon: Megaphone },
    { label: "Complaints", href: "/parent/complaints", icon: MessageSquareWarning },
    { label: "Announcements", href: "/parent/announcements", icon: Megaphone },
    { label: "LMS", href: "/parent/lms", icon: BookOpen },
  ],
  STUDENT: [
    { label: "Dashboard", href: "/student/dashboard", icon: LayoutDashboard },
    { label: "My Profile", href: "/student/profile", icon: Users },
    { label: "Subjects", href: "/student/subjects", icon: BookOpen },
    { label: "Timetable", href: "/student/timetable", icon: CalendarCheck },
    { label: "Assignments", href: "/student/assignments", icon: BookOpen },
    { label: "Attendance", href: "/student/attendance", icon: CalendarCheck },
    { label: "LMS", href: "/student/lms", icon: BookOpen },
    { label: "Results", href: "/student/results", icon: FileBarChart },
    { label: "Report Card", href: "/student/report-card", icon: FileBarChart },
    { label: "Announcements", href: "/student/announcements", icon: Megaphone },
  ],
  REGISTRAR: [
    { label: "Dashboard", href: "/registrar/dashboard", icon: LayoutDashboard },
    { label: "Applications", href: "/registrar/applications", icon: Users },
    { label: "Admissions", href: "/registrar/admissions", icon: Users },
    { label: "Student Records", href: "/registrar/student-records", icon: Users },
    { label: "Class Placement", href: "/registrar/class-placement", icon: Building2 },
    { label: "Parent Records", href: "/registrar/parent-records", icon: Users },
    { label: "Documents", href: "/registrar/documents", icon: FileBarChart },
    { label: "ID Cards", href: "/registrar/id-cards", icon: FileBarChart },
  ],
};
