// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/accountant/[section]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accountant/[section]">> = Specific
  const handler = {} as typeof import("../../src/app/accountant/[section]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/accountant/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accountant/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/accountant/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/[section]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/[section]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/[section]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/academic-calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/academic-calendar">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/academic-calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/branding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/branding">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/branding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/config-engine/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/config-engine">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/config-engine/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/setup">> = Specific
  const handler = {} as typeof import("../../src/app/admin/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/create-account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create-account">> = Specific
  const handler = {} as typeof import("../../src/app/create-account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/invoice/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/invoice/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/parent/[section]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parent/[section]">> = Specific
  const handler = {} as typeof import("../../src/app/parent/[section]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/parent/children/[childId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parent/children/[childId]">> = Specific
  const handler = {} as typeof import("../../src/app/parent/children/[childId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/parent/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parent/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/parent/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/receipt/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/receipt/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/receipt/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/registrar/[section]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registrar/[section]">> = Specific
  const handler = {} as typeof import("../../src/app/registrar/[section]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/registrar/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registrar/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/registrar/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reports/[studentId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/[studentId]">> = Specific
  const handler = {} as typeof import("../../src/app/reports/[studentId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/student/[section]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/[section]">> = Specific
  const handler = {} as typeof import("../../src/app/student/[section]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/student/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/student/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/teacher/[section]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/[section]">> = Specific
  const handler = {} as typeof import("../../src/app/teacher/[section]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/teacher/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/teacher/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/academic/sessions/[id]/activate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/academic/sessions/[id]/activate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/academic/sessions/[id]/activate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/academic/sessions/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/academic/sessions/[id]/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/academic/sessions/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/academic/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/academic/sessions">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/academic/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/academic/terms/[id]/activate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/academic/terms/[id]/activate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/academic/terms/[id]/activate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/academic/terms/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/academic/terms/[id]/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/academic/terms/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/academic/terms/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/academic/terms">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/academic/terms/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/branding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/branding">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/branding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/complaints/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/complaints/[id]/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/complaints/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/finance/fee-groups/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/finance/fee-groups/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/finance/fee-groups/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/finance/fee-groups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/finance/fee-groups">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/finance/fee-groups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/finance/fee-items/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/finance/fee-items/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/finance/fee-items/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/finance/fee-items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/finance/fee-items">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/finance/fee-items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/invoices/contests/review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/invoices/contests/review">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/invoices/contests/review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/invoices/contests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/invoices/contests">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/invoices/contests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/invoices/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/invoices/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/invoices/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/payments/proofs/[paymentId]/review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/payments/proofs/[paymentId]/review">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/payments/proofs/[paymentId]/review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/payments/proofs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/payments/proofs">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/payments/proofs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/results/review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/results/review">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/results/review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/settings/config/[id]/activate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/settings/config/[id]/activate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/settings/config/[id]/activate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/settings/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/settings/config">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/settings/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/setup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/setup">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/setup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/uploads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/uploads">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/uploads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/context/session-term/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/context/session-term">> = Specific
  const handler = {} as typeof import("../../src/app/api/context/session-term/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/latest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/latest">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/latest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/parent/complaints/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/parent/complaints">> = Specific
  const handler = {} as typeof import("../../src/app/api/parent/complaints/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/parent/invoices/contest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/parent/invoices/contest">> = Specific
  const handler = {} as typeof import("../../src/app/api/parent/invoices/contest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/parent/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/parent/messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/parent/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/parent/payments/notify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/parent/payments/notify">> = Specific
  const handler = {} as typeof import("../../src/app/api/parent/payments/notify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/parent/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/parent/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/parent/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/teacher/attendance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/teacher/attendance">> = Specific
  const handler = {} as typeof import("../../src/app/api/teacher/attendance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/teacher/scores/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/teacher/scores">> = Specific
  const handler = {} as typeof import("../../src/app/api/teacher/scores/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
