// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/accountant/[section]" | "/accountant/dashboard" | "/admin/[section]" | "/admin/dashboard" | "/admin/settings" | "/admin/settings/academic-calendar" | "/admin/settings/branding" | "/admin/settings/config-engine" | "/admin/setup" | "/create-account" | "/invoice/[id]" | "/login" | "/parent/[section]" | "/parent/children/[childId]" | "/parent/dashboard" | "/receipt/[id]" | "/registrar/[section]" | "/registrar/dashboard" | "/reports/[studentId]" | "/student/[section]" | "/student/dashboard" | "/super-admin/dashboard" | "/teacher/[section]" | "/teacher/dashboard"
type AppRouteHandlerRoutes = "/api/admin/academic/sessions" | "/api/admin/academic/sessions/[id]/activate" | "/api/admin/academic/sessions/[id]/status" | "/api/admin/academic/terms" | "/api/admin/academic/terms/[id]/activate" | "/api/admin/academic/terms/[id]/status" | "/api/admin/branding" | "/api/admin/complaints/[id]/status" | "/api/admin/finance/fee-groups" | "/api/admin/finance/fee-groups/[id]" | "/api/admin/finance/fee-items" | "/api/admin/finance/fee-items/[id]" | "/api/admin/invoices/contests" | "/api/admin/invoices/contests/review" | "/api/admin/invoices/generate" | "/api/admin/payments/proofs" | "/api/admin/payments/proofs/[paymentId]/review" | "/api/admin/results/review" | "/api/admin/settings/config" | "/api/admin/settings/config/[id]/activate" | "/api/admin/setup" | "/api/admin/uploads" | "/api/auth/[...nextauth]" | "/api/context/session-term" | "/api/notifications/latest" | "/api/parent/complaints" | "/api/parent/invoices/contest" | "/api/parent/messages" | "/api/parent/payments/notify" | "/api/parent/profile" | "/api/teacher/attendance" | "/api/teacher/scores"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/accountant/[section]": { "section": string; }
  "/accountant/dashboard": {}
  "/admin/[section]": { "section": string; }
  "/admin/dashboard": {}
  "/admin/settings": {}
  "/admin/settings/academic-calendar": {}
  "/admin/settings/branding": {}
  "/admin/settings/config-engine": {}
  "/admin/setup": {}
  "/api/admin/academic/sessions": {}
  "/api/admin/academic/sessions/[id]/activate": { "id": string; }
  "/api/admin/academic/sessions/[id]/status": { "id": string; }
  "/api/admin/academic/terms": {}
  "/api/admin/academic/terms/[id]/activate": { "id": string; }
  "/api/admin/academic/terms/[id]/status": { "id": string; }
  "/api/admin/branding": {}
  "/api/admin/complaints/[id]/status": { "id": string; }
  "/api/admin/finance/fee-groups": {}
  "/api/admin/finance/fee-groups/[id]": { "id": string; }
  "/api/admin/finance/fee-items": {}
  "/api/admin/finance/fee-items/[id]": { "id": string; }
  "/api/admin/invoices/contests": {}
  "/api/admin/invoices/contests/review": {}
  "/api/admin/invoices/generate": {}
  "/api/admin/payments/proofs": {}
  "/api/admin/payments/proofs/[paymentId]/review": { "paymentId": string; }
  "/api/admin/results/review": {}
  "/api/admin/settings/config": {}
  "/api/admin/settings/config/[id]/activate": { "id": string; }
  "/api/admin/setup": {}
  "/api/admin/uploads": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/context/session-term": {}
  "/api/notifications/latest": {}
  "/api/parent/complaints": {}
  "/api/parent/invoices/contest": {}
  "/api/parent/messages": {}
  "/api/parent/payments/notify": {}
  "/api/parent/profile": {}
  "/api/teacher/attendance": {}
  "/api/teacher/scores": {}
  "/create-account": {}
  "/invoice/[id]": { "id": string; }
  "/login": {}
  "/parent/[section]": { "section": string; }
  "/parent/children/[childId]": { "childId": string; }
  "/parent/dashboard": {}
  "/receipt/[id]": { "id": string; }
  "/registrar/[section]": { "section": string; }
  "/registrar/dashboard": {}
  "/reports/[studentId]": { "studentId": string; }
  "/student/[section]": { "section": string; }
  "/student/dashboard": {}
  "/super-admin/dashboard": {}
  "/teacher/[section]": { "section": string; }
  "/teacher/dashboard": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
